#!/bin/bash

# System Info Report Script - First Assignment

# Get the current date and time
mydate=$(date)

# Get the system's hostname
myhostname=$(hostname)

# Get the username running the script
myusername=$(whoami)

# Get the OS name and version from the system's release info
source /etc/os-release
os=$PRETTY_NAME

# Get how long the system has been up
uptime_info=$(uptime -p)

# Get the CPU model name (first one listed)
cpu=$(lshw -C processor 2>/dev/null | grep 'product:' | head -n 1)

# Get the total amount of installed RAM (using sudo to access dmidecode)
ram=$(sudo dmidecode -t memory | grep -i "Size:" | grep -v "No Module Installed" | awk '{sum += $2} END {print sum " MB"}')

# Get info about all installed disks (product name and size)
disks=$(sudo lshw -class disk 2>/dev/null | grep -E 'product:|size:' | grep -v "configuration:")

# Get the name of the video card
video=$(sudo lshw -C display 2>/dev/null | grep 'product:' | head -n 1)

# Find the default network interface used to reach the internet
default_if=$(ip route | grep default | awk '{print $5}')

# Get the IP address of that interface
host_ip=$(ip -4 addr show $default_if | grep inet | awk '{print $2}' | cut -d/ -f1)

# Get the default gateway IP address
gateway_ip=$(ip route | grep default | awk '{print $3}')

# Get the first DNS server from the resolv.conf file
dns_server=$(grep nameserver /etc/resolv.conf | head -n 1 | awk '{print $2}')

# Get a list of logged-in users (unique and comma-separated)
users=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',' | sed 's/,$//')

# Show how much free space is available on each mount point
diskspace=$(df -h --output=target,avail | tail -n +2)

# Count the total number of running processes
processes=$(ps aux | wc -l)

# Show system load averages (1, 5, and 15-minute intervals)
loadavg=$(uptime | awk -F'load average:' '{print $2}')

# Show ports that are listening for connections (TCP/UDP)
ports=$(ss -tuln | grep LISTEN | awk '{print $5}' | awk -F: '{print $NF}' | sort -n | uniq | tr '\n' ',' | sed 's/,$//')

# Get the status of the UFW firewall
ufw_status=$(sudo ufw status | grep Status | awk '{print $2}')

# Now display everything in a nice, readable format
cat <<EOF

System Report for $myhostname generated by $myusername, on $mydate

System Information
------------------
OS: $os
Uptime: $uptime_info
CPU: $cpu
RAM: $ram
Disk(s):
$disks
Video: $video
Host Address: $host_ip
Gateway IP: $gateway_ip
DNS Server: $dns_server

System Status
-------------
Users Logged In: $users
Disk Space:
$diskspace
Process Count: $processes
Load Averages:$loadavg
Listening Network Ports: $ports
UFW Status: $ufw_status

EOF

